In [13]:
import plotly.graph_objects as go
import models
import diagnostics
import os
import preprocess
import plots
import utils
import numpy as np
import pandas as pd

### Setup

In [14]:
file_path = os.getenv("FILE_PATH")
SNP_file = './data/S&P 500 Index.csv'
VIX_file = './data/S&P 500 VIX.csv'

In [15]:
# Scale is applied to log returns in order to improve numerical stability of models
SCALE = 100

### S&P500

In [16]:
SNP_processed = preprocess.preprocess_data(SNP_file, 'price', 'log_returns')
SNP_processed = utils.upscale_columns(
  SNP_processed, ['log_returns'], SCALE
)
SNP_processed.head()

              price  log_returns
date
2015-01-05  2020.58    -1.844722
2015-01-06  2002.61    -0.893327
2015-01-07  2025.90     1.156272
2015-01-08  2062.14     1.773023
2015-01-09  2044.81    -0.843940

In [17]:
snp_obj = utils.GarchFbmReturnForecast(SNP_processed)
snp_obj.df.head()

              price  log_returns
date
2015-01-05  2020.58    -1.844722
2015-01-06  2002.61    -0.893327
2015-01-07  2025.90     1.156272
2015-01-08  2062.14     1.773023
2015-01-09  2044.81    -0.843940

In [18]:
snp_garch_fbm = utils.apply_rolling_predictions_from_start(snp_obj, '2017-01-01', 250)
snp_garch_fbm.head()

Day 252...
Day 253...
Day 254...
Day 255...
Day 256...
Day 257...
Day 258...
Day 259...
Day 260...
Day 261...
Day 262...
Day 263...
Day 264...
Day 265...
Day 266...
Day 267...
Day 268...
Day 269...
Day 270...
Day 271...
Day 272...
Day 273...
Day 274...
Day 275...
Day 276...
Day 277...
Day 278...
Day 279...
Day 280...
Day 281...
Day 282...
Day 283...
Day 284...
Day 285...
Day 286...
Day 287...
Day 288...
Day 289...
Day 290...
Day 291...
Day 292...
Day 293...
Day 294...
Day 295...
Day 296...
Day 297...
Day 298...
Day 299...
Day 300...
Day 301...
Day 302...
Day 303...
Day 304...
Day 305...
Day 306...
Day 307...
Day 308...
Day 309...
Day 310...
Day 311...
Day 312...
Day 313...
Day 314...
Day 315...
Day 316...
Day 317...
Day 318...
Day 319...
Day 320...
Day 321...
Day 322...
Day 323...
Day 324...
Day 325...
Day 326...
Day 327...
Day 328...
Day 329...
Day 330...
Day 331...
Day 332...
Day 333...
Day 334...
Day 335...
Day 336...
Day 337...
Day 338...
Day 339...
Day 340...
Day 341...
Day 342...
Day 343...
Day 344...
Day 345...
Day 346...
Day 347...
Day 348...
Day 349...
Day 350...
Day 351...
Day 352...
Day 353...
Day 354...
Day 355...
Day 356...
Day 357...
Day 358...
Day 359...
Day 360...
Day 361...
Day 362...
Day 363...
Day 364...
Day 365...
Day 366...
Day 367...
Day 368...
Day 369...
Day 370...
Day 371...
Day 372...
Day 373...
Day 374...
Day 375...
Day 376...
Day 377...
Day 378...
Day 379...
Day 380...
Day 381...
Day 382...
Day 383...
Day 384...
Day 385...
Day 386...
Day 387...
Day 388...
Day 389...
Day 390...
Day 391...
Day 392...
Day 393...
Day 394...
Day 395...
Day 396...
Day 397...
Day 398...
Day 399...
Day 400...
Day 401...
Day 402...
Day 403...
Day 404...
Day 405...
Day 406...
Day 407...
Day 408...
Day 409...
Day 410...
Day 411...
Day 412...
Day 413...
Day 414...
Day 415...
Day 416...
Day 417...
Day 418...
Day 419...
Day 420...
Day 421...
Day 422...
Day 423...
Day 424...
Day 425...
Day 426...
Day 427...
Day 428...
Day 429...
Day 430...
Day 431...
Day 432...
Day 433...
Day 434...
Day 435...
Day 436...
Day 437...
Day 438...
Day 439...
Day 440...
Day 441...
Day 442...
Day 443...
Day 444...
Day 445...
Day 446...
Day 447...
Day 448...
Day 449...
Day 450...
Day 451...
Day 452...
Day 453...
Day 454...
Day 455...
Day 456...
Day 457...
Day 458...
Day 459...
Day 460...
Day 461...
Day 462...
Day 463...
Day 464...
Day 465...
Day 466...
Day 467...
Day 468...
Day 469...
Day 470...
Day 471...
Day 472...
Day 473...
Day 474...
Day 475...
Day 476...
Day 477...
Day 478...
Day 479...
Day 480...
Day 481...
Day 482...
Day 483...
Day 484...
Day 485...
Day 486...
Day 487...
Day 488...
Day 489...
Day 490...
Day 491...
Day 492...
Day 493...
Day 494...
Day 495...
Day 496...
Day 497...
Day 498...
Day 499...
Day 500...
Day 501...
Day 502...
Day 503...
Day 504...
Day 505...
Day 506...
Day 507...
Day 508...
Day 509...
Day 510...
Day 511...
Day 512...
Day 513...
Day 514...
Day 515...
Day 516...
Day 517...
Day 518...
Day 519...
Day 520...
Day 521...
Day 522...
Day 523...
Day 524...
Day 525...
Day 526...
Day 527...
Day 528...
Day 529...
Day 530...
Day 531...
Day 532...
Day 533...
Day 534...
Day 535...
Day 536...
Day 537...
Day 538...
Day 539...
Day 540...
Day 541...
Day 542...
Day 543...
Day 544...
Day 545...
Day 546...
Day 547...
Day 548...
Day 549...
Day 550...
Day 551...
Day 552...
Day 553...
Day 554...
Day 555...
Day 556...
Day 557...
Day 558...
Day 559...
Day 560...
Day 561...
Day 562...
Day 563...
Day 564...
Day 565...
Day 566...
Day 567...
Day 568...
Day 569...
Day 570...
Day 571...
Day 572...
Day 573...
Day 574...
Day 575...
Day 576...
Day 577...
Day 578...
Day 579...
Day 580...
Day 581...
Day 582...
Day 583...
Day 584...
Day 585...
Day 586...
Day 587...
Day 588...
Day 589...
Day 590...
Day 591...
Day 592...
Day 593...
Day 594...
Day 595...
Day 596...
Day 597...
Day 598...
Day 599...
Day 600...
Day 601...
Day 602...
Day 603...
Day 604...
Day 605...
Day 606...
Day 607...
Day 608...
Day 609...
Day 610...
Day 611...
Day 612...
Day 613...
Day 614...
Day 615...
Day 616...
Day 617...
Day 618...
Day 619...
Day 620...
Day 621...
Day 622...
Day 623...
Day 624...
Day 625...
Day 626...
Day 627...
Day 628...
Day 629...
Day 630...
Day 631...
Day 632...
Day 633...
Day 634...
Day 635...
Day 636...
Day 637...
Day 638...
Day 639...
Day 640...
Day 641...
Day 642...
Day 643...
Day 644...
Day 645...
Day 646...
Day 647...
Day 648...
Day 649...
Day 650...
Day 651...
Day 652...
Day 653...
Day 654...
Day 655...
Day 656...
Day 657...
Day 658...
Day 659...
Day 660...
Day 661...
Day 662...
Day 663...
Day 664...
Day 665...
Day 666...
Day 667...
Day 668...
Day 669...
Day 670...
Day 671...
Day 672...
Day 673...
Day 674...
Day 675...
Day 676...
Day 677...
Day 678...
Day 679...
Day 680...
Day 681...
Day 682...
Day 683...
Day 684...
Day 685...
Day 686...
Day 687...
Day 688...
Day 689...
Day 690...
Day 691...
Day 692...
Day 693...
Day 694...
Day 695...
Day 696...
Day 697...
Day 698...
Day 699...
Day 700...
Day 701...
Day 702...
Day 703...
Day 704...
Day 705...
Day 706...
Day 707...
Day 708...
Day 709...
Day 710...
Day 711...
Day 712...
Day 713...
Day 714...
Day 715...
Day 716...
Day 717...
Day 718...
Day 719...
Day 720...
Day 721...
Day 722...
Day 723...
Day 724...
Day 725...
Day 726...
Day 727...
Day 728...
Day 729...
Day 730...
Day 731...
Day 732...
Day 733...
Day 734...
Day 735...
Day 736...
Day 737...
Day 738...
Day 739...
Day 740...
Day 741...
Day 742...
Day 743...
Day 744...
Day 745...
Day 746...
Day 747...
Day 748...
Day 749...
Day 750...
Day 751...
Day 752...
Day 753...
Day 754...
Day 755...
Day 756...
Day 757...
Day 758...
Day 759...
Day 760...
Day 761...
Day 762...
Day 763...
Day 764...
Day 765...
Day 766...
Day 767...
Day 768...
Day 769...
Day 770...
Day 771...
Day 772...
Day 773...
Day 774...
Day 775...
Day 776...
Day 777...
Day 778...
Day 779...
Day 780...
Day 781...
Day 782...
Day 783...
Day 784...
Day 785...
Day 786...
Day 787...
Day 788...
Day 789...
Day 790...
Day 791...
Day 792...
Day 793...
Day 794...
Day 795...
Day 796...
Day 797...
Day 798...
Day 799...
Day 800...
Day 801...
Day 802...
Day 803...
Day 804...
Day 805...
Day 806...
Day 807...
Day 808...
Day 809...
Day 810...
Day 811...
Day 812...
Day 813...
Day 814...
Day 815...
Day 816...
Day 817...
Day 818...
Day 819...
Day 820...
Day 821...
Day 822...
Day 823...
Day 824...
Day 825...
Day 826...
Day 827...
Day 828...
Day 829...
Day 830...
Day 831...
Day 832...
Day 833...
Day 834...
Day 835...
Day 836...
Day 837...
Day 838...
Day 839...
Day 840...
Day 841...
Day 842...
Day 843...
Day 844...
Day 845...
Day 846...
Day 847...
Day 848...
Day 849...
Day 850...
Day 851...
Day 852...
Day 853...
Day 854...
Day 855...
Day 856...
Day 857...
Day 858...
Day 859...
Day 860...
Day 861...
Day 862...
Day 863...
Day 864...
Day 865...
Day 866...
Day 867...
Day 868...
Day 869...
Day 870...
Day 871...
Day 872...
Day 873...
Day 874...
Day 875...
Day 876...
Day 877...
Day 878...
Day 879...
Day 880...
Day 881...
Day 882...
Day 883...
Day 884...
Day 885...
Day 886...
Day 887...
Day 888...
Day 889...
Day 890...
Day 891...
Day 892...
Day 893...
Day 894...
Day 895...
Day 896...
Day 897...
Day 898...
Day 899...
Day 900...
Day 901...
Day 902...
Day 903...
Day 904...
Day 905...
Day 906...
Day 907...
Day 908...
Day 909...
Day 910...
Day 911...
Day 912...
Day 913...
Day 914...
Day 915...
Day 916...
Day 917...
Day 918...
Day 919...
Day 920...
Day 921...
Day 922...
Day 923...
Day 924...
Day 925...
Day 926...
Day 927...
Day 928...
Day 929...
Day 930...
Day 931...
Day 932...
Day 933...
Day 934...
Day 935...
Day 936...
Day 937...
Day 938...
Day 939...
Day 940...
Day 941...
Day 942...
Day 943...
Day 944...
Day 945...
Day 946...
Day 947...
Day 948...
Day 949...
Day 950...
Day 951...
Day 952...
Day 953...
Day 954...
Day 955...
Day 956...
Day 957...
Day 958...
Day 959...
Day 960...
Day 961...
Day 962...
Day 963...
Day 964...
Day 965...
Day 966...
Day 967...
Day 968...
Day 969...
Day 970...
Day 971...
Day 972...
Day 973...
Day 974...
Day 975...
Day 976...
Day 977...
Day 978...
Day 979...
Day 980...
Day 981...
Day 982...
Day 983...
Day 984...
Day 985...
Day 986...
Day 987...
Day 988...
Day 989...
Day 990...
Day 991...
Day 992...
Day 993...
Day 994...
Day 995...
Day 996...
Day 997...
Day 998...
Day 999...
Day 1000...
Day 1001...
Day 1002...
Day 1003...
Day 1004...
Day 1005...
Day 1006...
Day 1007...
Day 1008...
Day 1009...
Day 1010...
Day 1011...
Day 1012...
Day 1013...
Day 1014...
Day 1015...
Day 1016...
Day 1017...
Day 1018...
Day 1019...
Day 1020...
Day 1021...
Day 1022...
Day 1023...
Day 1024...
Day 1025...
Day 1026...
Day 1027...
Day 1028...
Day 1029...
Day 1030...
Day 1031...
Day 1032...
Day 1033...
Day 1034...
Day 1035...
Day 1036...
Day 1037...
Day 1038...
Day 1039...
Day 1040...
Day 1041...
Day 1042...
Day 1043...
Day 1044...
Day 1045...
Day 1046...
Day 1047...
Day 1048...
Day 1049...
Day 1050...
Day 1051...
Day 1052...
Day 1053...
Day 1054...
Day 1055...
Day 1056...
Day 1057...
Day 1058...
Day 1059...
Day 1060...
Day 1061...
Day 1062...
Day 1063...
Day 1064...
Day 1065...
Day 1066...
Day 1067...
Day 1068...
Day 1069...
Day 1070...
Day 1071...
Day 1072...
Day 1073...
Day 1074...
Day 1075...
Day 1076...
Day 1077...
Day 1078...
Day 1079...
Day 1080...
Day 1081...
Day 1082...
Day 1083...
Day 1084...
Day 1085...
Day 1086...
Day 1087...
Day 1088...
Day 1089...
Day 1090...
Day 1091...
Day 1092...
Day 1093...
Day 1094...
Day 1095...
Day 1096...
Day 1097...
Day 1098...
Day 1099...
Day 1100...
Day 1101...
Day 1102...
Day 1103...
Day 1104...
Day 1105...
Day 1106...
Day 1107...
Day 1108...
Day 1109...
Day 1110...
Day 1111...
Day 1112...
Day 1113...
Day 1114...
Day 1115...
Day 1116...
Day 1117...
Day 1118...
Day 1119...
Day 1120...
Day 1121...
Day 1122...
Day 1123...
Day 1124...
Day 1125...
Day 1126...
Day 1127...
Day 1128...
Day 1129...
Day 1130...
Day 1131...
Day 1132...
Day 1133...
Day 1134...
Day 1135...
Day 1136...
Day 1137...
Day 1138...
Day 1139...
Day 1140...
Day 1141...
Day 1142...
Day 1143...
Day 1144...
Day 1145...
Day 1146...
Day 1147...
Day 1148...
Day 1149...
Day 1150...
Day 1151...
Day 1152...
Day 1153...
Day 1154...
Day 1155...
Day 1156...
Day 1157...
Day 1158...
Day 1159...
Day 1160...
Day 1161...
Day 1162...
Day 1163...
Day 1164...
Day 1165...
Day 1166...
Day 1167...
Day 1168...
Day 1169...
Day 1170...
Day 1171...
Day 1172...
Day 1173...
Day 1174...
Day 1175...
Day 1176...
Day 1177...
Day 1178...
Day 1179...
Day 1180...
Day 1181...
Day 1182...
Day 1183...
Day 1184...
Day 1185...
Day 1186...
Day 1187...
Day 1188...
Day 1189...
Day 1190...
Day 1191...
Day 1192...
Day 1193...
Day 1194...
Day 1195...
Day 1196...
Day 1197...
Day 1198...
Day 1199...
Day 1200...
Day 1201...
Day 1202...
Day 1203...
Day 1204...
Day 1205...
Day 1206...
Day 1207...
Day 1208...
Day 1209...
Day 1210...
Day 1211...
Day 1212...
Day 1213...
Day 1214...
Day 1215...
Day 1216...
Day 1217...
Day 1218...
Day 1219...
Day 1220...
Day 1221...
Day 1222...
Day 1223...
Day 1224...
Day 1225...
Day 1226...
Day 1227...
Day 1228...
Day 1229...
Day 1230...
Day 1231...
Day 1232...
Day 1233...
Day 1234...
Day 1235...
Day 1236...
Day 1237...
Day 1238...
Day 1239...
Day 1240...
Day 1241...
Day 1242...
Day 1243...
Day 1244...
Day 1245...
Day 1246...
Day 1247...
Day 1248...
Day 1249...
Day 1250...
Day 1251...
Day 1252...
Day 1253...
Day 1254...
Day 1255...
Day 1256...
Day 1257...
Day 1258...
Day 1259...
Day 1260...
Day 1261...
Day 1262...
Day 1263...
Day 1264...
Day 1265...
Day 1266...
Day 1267...
Day 1268...
Day 1269...
Day 1270...
Day 1271...
Day 1272...
Day 1273...
Day 1274...
Day 1275...
Day 1276...
Day 1277...
Day 1278...
Day 1279...
Day 1280...
Day 1281...
Day 1282...
Day 1283...
Day 1284...
Day 1285...
Day 1286...
Day 1287...
Day 1288...
Day 1289...
Day 1290...
Day 1291...
Day 1292...
Day 1293...
Day 1294...
Day 1295...
Day 1296...
Day 1297...
Day 1298...
Day 1299...
Day 1300...
Day 1301...
Day 1302...
Day 1303...
Day 1304...
Day 1305...
Day 1306...
Day 1307...
Day 1308...
Day 1309...
Day 1310...
Day 1311...
Day 1312...
Day 1313...
Day 1314...
Day 1315...
Day 1316...
Day 1317...
Day 1318...
Day 1319...
Day 1320...
Day 1321...
Day 1322...
Day 1323...
Day 1324...
Day 1325...
Day 1326...
Day 1327...
Day 1328...
Day 1329...
Day 1330...
Day 1331...
Day 1332...
Day 1333...
Day 1334...
Day 1335...
Day 1336...
Day 1337...
Day 1338...
Day 1339...
Day 1340...
Day 1341...
Day 1342...
Day 1343...
Day 1344...
Day 1345...
Day 1346...
Day 1347...
Day 1348...
Day 1349...
Day 1350...
Day 1351...
Day 1352...
Day 1353...
Day 1354...
Day 1355...
Day 1356...
Day 1357...
Day 1358...
Day 1359...
Day 1360...
Day 1361...
Day 1362...
Day 1363...
Day 1364...
Day 1365...
Day 1366...
Day 1367...
Day 1368...
Day 1369...
Day 1370...
Day 1371...
Day 1372...
Day 1373...
Day 1374...
Day 1375...
Day 1376...
Day 1377...
Day 1378...
Day 1379...
Day 1380...
Day 1381...
Day 1382...
Day 1383...
Day 1384...
Day 1385...
Day 1386...
Day 1387...
Day 1388...
Day 1389...
Day 1390...
Day 1391...
Day 1392...
Day 1393...
Day 1394...
Day 1395...
Day 1396...
Day 1397...
Day 1398...
Day 1399...
Day 1400...
Day 1401...
Day 1402...
Day 1403...
Day 1404...
Day 1405...
Day 1406...
Day 1407...
Day 1408...
Day 1409...
Day 1410...
Day 1411...
Day 1412...
Day 1413...
Day 1414...
Day 1415...
Day 1416...
Day 1417...
Day 1418...
Day 1419...
Day 1420...
Day 1421...
Day 1422...
Day 1423...
Day 1424...
Day 1425...
Day 1426...
Day 1427...
Day 1428...
Day 1429...
Day 1430...
Day 1431...
Day 1432...
Day 1433...
Day 1434...
Day 1435...
Day 1436...
Day 1437...
Day 1438...
Day 1439...
Day 1440...
Day 1441...
Day 1442...
Day 1443...
Day 1444...
Day 1445...
Day 1446...
Day 1447...
Day 1448...
Day 1449...
Day 1450...
Day 1451...
Day 1452...
Day 1453...
Day 1454...
Day 1455...
Day 1456...
Day 1457...
Day 1458...
Day 1459...
Day 1460...
Day 1461...
Day 1462...
Day 1463...
Day 1464...
Day 1465...
Day 1466...
Day 1467...
Day 1468...
Day 1469...
Day 1470...
Day 1471...
Day 1472...
Day 1473...
Day 1474...
Day 1475...
Day 1476...
Day 1477...
Day 1478...
Day 1479...
Day 1480...
Day 1481...
Day 1482...
Day 1483...
Day 1484...
Day 1485...
Day 1486...
Day 1487...
Day 1488...
Day 1489...
Day 1490...
Day 1491...
Day 1492...
Day 1493...
Day 1494...
Day 1495...
Day 1496...
Day 1497...
Day 1498...
Day 1499...
Day 1500...
Day 1501...
Day 1502...
Day 1503...
Day 1504...
Day 1505...
Day 1506...
Day 1507...
Day 1508...
Day 1509...
Day 1510...
Day 1511...
Day 1512...
Day 1513...
Day 1514...
Day 1515...
Day 1516...
Day 1517...
Day 1518...
Day 1519...
Day 1520...
Day 1521...
Day 1522...
Day 1523...
Day 1524...
Day 1525...
Day 1526...
Day 1527...
Day 1528...
Day 1529...
Day 1530...
Day 1531...
Day 1532...
Day 1533...
Day 1534...
Day 1535...
Day 1536...
Day 1537...
Day 1538...
Day 1539...
Day 1540...
Day 1541...
Day 1542...
Day 1543...
Day 1544...
Day 1545...
Day 1546...
Day 1547...
Day 1548...
Day 1549...
Day 1550...
Day 1551...
Day 1552...
Day 1553...
Day 1554...
Day 1555...
Day 1556...
Day 1557...
Day 1558...
Day 1559...
Day 1560...
Day 1561...
Day 1562...
Day 1563...
Day 1564...
Day 1565...
Day 1566...
Day 1567...
Day 1568...
Day 1569...
Day 1570...
Day 1571...
Day 1572...
Day 1573...
Day 1574...
Day 1575...
Day 1576...
Day 1577...
Day 1578...
Day 1579...
Day 1580...
Day 1581...
Day 1582...
Day 1583...
Day 1584...
Day 1585...
Day 1586...
Day 1587...
Day 1588...
Day 1589...
Day 1590...
Day 1591...
Day 1592...
Day 1593...
Day 1594...
Day 1595...
Day 1596...
Day 1597...
Day 1598...
Day 1599...
Day 1600...
Day 1601...
Day 1602...
Day 1603...
Day 1604...
Day 1605...
Day 1606...
Day 1607...
Day 1608...
Day 1609...
Day 1610...
Day 1611...
Day 1612...
Day 1613...
Day 1614...
Day 1615...
Day 1616...
Day 1617...
Day 1618...
Day 1619...
Day 1620...
Day 1621...
Day 1622...
Day 1623...
Day 1624...
Day 1625...
Day 1626...
Day 1627...
Day 1628...
Day 1629...
Day 1630...
Day 1631...
Day 1632...
Day 1633...
Day 1634...
Day 1635...
Day 1636...
Day 1637...
Day 1638...
Day 1639...
Day 1640...
Day 1641...
Day 1642...
Day 1643...
Day 1644...
Day 1645...
Day 1646...
Day 1647...
Day 1648...
Day 1649...
Day 1650...
Day 1651...
Day 1652...
Day 1653...
Day 1654...
Day 1655...
Day 1656...
Day 1657...
Day 1658...
Day 1659...
Day 1660...
Day 1661...
Day 1662...
Day 1663...
Day 1664...
Day 1665...
Day 1666...
Day 1667...
Day 1668...
Day 1669...
Day 1670...
Day 1671...
Day 1672...
Day 1673...
Day 1674...
Day 1675...
Day 1676...
Day 1677...
Day 1678...
Day 1679...
Day 1680...
Day 1681...
Day 1682...
Day 1683...
Day 1684...
Day 1685...
Day 1686...
Day 1687...
Day 1688...
Day 1689...
Day 1690...
Day 1691...
Day 1692...
Day 1693...
Day 1694...
Day 1695...
Day 1696...
Day 1697...
Day 1698...
Day 1699...
Day 1700...
Day 1701...
Day 1702...
Day 1703...
Day 1704...
Day 1705...
Day 1706...
Day 1707...
Day 1708...
Day 1709...
Day 1710...
Day 1711...
Day 1712...
Day 1713...
Day 1714...
Day 1715...
Day 1716...
Day 1717...
Day 1718...
Day 1719...
Day 1720...
Day 1721...
Day 1722...
Day 1723...
Day 1724...
Day 1725...
Day 1726...
Day 1727...
Day 1728...
Day 1729...
Day 1730...
Day 1731...
Day 1732...
Day 1733...
Day 1734...
Day 1735...
Day 1736...
Day 1737...
Day 1738...
Day 1739...
Day 1740...
Day 1741...
Day 1742...
Day 1743...
Day 1744...
Day 1745...
Day 1746...
Day 1747...
Day 1748...
Day 1749...
Day 1750...
Day 1751...
Day 1752...
Day 1753...
Day 1754...
Day 1755...
Day 1756...
Day 1757...
Day 1758...
Day 1759...
Day 1760...
Day 1761...
Day 1762...
Day 1763...
Day 1764...
Day 1765...
Day 1766...
Day 1767...
Day 1768...
Day 1769...
Day 1770...
Day 1771...
Day 1772...
Day 1773...
Day 1774...
Day 1775...
Day 1776...
Day 1777...
Day 1778...
Day 1779...
Day 1780...
Day 1781...
Day 1782...
Day 1783...
Day 1784...
Day 1785...
Day 1786...
Day 1787...
Day 1788...
Day 1789...
Day 1790...
Day 1791...
Day 1792...
Day 1793...
Day 1794...
Day 1795...
Day 1796...
Day 1797...
Day 1798...
Day 1799...
Day 1800...
Day 1801...
Day 1802...
Day 1803...
Day 1804...
Day 1805...
Day 1806...
Day 1807...
Day 1808...
Day 1809...
Day 1810...
Day 1811...
Day 1812...
Day 1813...
Day 1814...
Day 1815...
Day 1816...
Day 1817...
Day 1818...
Day 1819...
Day 1820...
Day 1821...
Day 1822...
Day 1823...
Day 1824...
Day 1825...
Day 1826...
Day 1827...
Day 1828...
Day 1829...
Day 1830...
Day 1831...
Day 1832...
Day 1833...
Day 1834...
Day 1835...
Day 1836...
Day 1837...
Day 1838...
Day 1839...
Day 1840...
Day 1841...
Day 1842...
Day 1843...
Day 1844...
Day 1845...
Day 1846...
Day 1847...
Day 1848...
Day 1849...
Day 1850...
Day 1851...
Day 1852...
Day 1853...
Day 1854...
Day 1855...
Day 1856...
Day 1857...
Day 1858...
Day 1859...
Day 1860...
Day 1861...
Day 1862...
Day 1863...
Day 1864...
Day 1865...
Day 1866...
Day 1867...
Day 1868...
Day 1869...
Day 1870...
Day 1871...
Day 1872...
Day 1873...
Day 1874...
Day 1875...
Day 1876...
Day 1877...
Day 1878...
Day 1879...
Day 1880...
Day 1881...
Day 1882...
Day 1883...
Day 1884...
Day 1885...
Day 1886...
Day 1887...
Day 1888...
Day 1889...
Day 1890...
Day 1891...
Day 1892...
Day 1893...
Day 1894...
Day 1895...
Day 1896...
Day 1897...
Day 1898...
Day 1899...
Day 1900...
Day 1901...
Day 1902...
Day 1903...
Day 1904...
Day 1905...
Day 1906...
Day 1907...
Day 1908...
Day 1909...
Day 1910...
Day 1911...
Day 1912...
Day 1913...
Day 1914...
Day 1915...
Day 1916...
Day 1917...
Day 1918...
Day 1919...
Day 1920...
Day 1921...
Day 1922...
Day 1923...
Day 1924...
Day 1925...
Day 1926...
Day 1927...
Day 1928...
Day 1929...
Day 1930...
Day 1931...
Day 1932...
Day 1933...
Day 1934...
Day 1935...
Day 1936...
Day 1937...
Day 1938...
Day 1939...
Day 1940...
Day 1941...
Day 1942...
Day 1943...
Day 1944...
Day 1945...
Day 1946...
Day 1947...
Day 1948...
Day 1949...
Day 1950...
Day 1951...
Day 1952...
Day 1953...
Day 1954...
Day 1955...
Day 1956...
Day 1957...
Day 1958...
Day 1959...
Day 1960...
Day 1961...
Day 1962...
Day 1963...
Day 1964...
Day 1965...
Day 1966...
Day 1967...
Day 1968...
Day 1969...
Day 1970...
Day 1971...
Day 1972...
Day 1973...
Day 1974...
Day 1975...
Day 1976...
Day 1977...
Day 1978...
Day 1979...
Day 1980...

              predicted  conditional_vol
2016-01-05  1984.106338         0.009140
2016-01-06  2016.651848         0.010580
2016-01-07  1960.296566         0.009492
2016-01-08  1917.298123         0.010463
2016-01-11  1966.664699         0.013987

In [19]:
snp_garch_fbm= utils.compute_log_returns(
  snp_garch_fbm,
  SNP_processed,
  "predicted",
  "predicted_log_returns"
)
snp_garch_fbm.head()

,predicted,conditional_vol,predicted_log_returns,price,log_returns
2016-01-06,2016.651848,0.010580,0.016270,1990.26,-1.320219
2016-01-07,1960.296566,0.009492,-0.028343,1943.09,-2.398579
2016-01-08,1917.298123,0.010463,-0.022179,1922.03,-1.089757
2016-01-11,1966.664699,0.013987,0.025422,1923.67,0.085290
2016-01-12,1914.131529,0.012946,-0.027075,1938.68,0.777251

In [20]:
# Rescale back scaled columns
snp_garch_fbm = utils.downscale_columns(
  snp_garch_fbm, ['log_returns'], SCALE
)
diagnostics.in_sample_diagnostics(snp_garch_fbm['predicted_log_returns'], snp_garch_fbm['log_returns'], snp_garch_fbm['conditional_vol'])

Jarque-Bera test p-value: 0.00001
Ljung-Box (residuals) p-value, 0.00000
Ljung-Box (residuals^2) p-value, 0.00000

In [21]:
snp_garch_fbm.head()

,predicted,conditional_vol,predicted_log_returns,price,log_returns
2016-01-06,2016.651848,0.010580,0.016270,1990.26,-0.013202
2016-01-07,1960.296566,0.009492,-0.028343,1943.09,-0.023986
2016-01-08,1917.298123,0.010463,-0.022179,1922.03,-0.010898
2016-01-11,1966.664699,0.013987,0.025422,1923.67,0.000853
2016-01-12,1914.131529,0.012946,-0.027075,1938.68,0.007773

In [22]:
snp_garch_fbm_var = snp_garch_fbm
snp_garch_fbm_var['VaR_99'] = snp_garch_fbm_var['predicted_log_returns'].rolling(250).quantile(0.01)
diagnostics.compute_var_violations(snp_garch_fbm_var, 'VaR_99', 'predicted_log_returns')

{'actual_exceedances': 29,
 'expected_exceedances': 20.12000000000002,
 'violation_ratio': 1.4413518886679908}

In [23]:
utils.compute_rmse(snp_garch_fbm_var, 'log_returns', 'predicted_log_returns')

0.02547617285891666

In [24]:
diagnostics.bernoulli_coverage_test(snp_garch_fbm_var, var_col='VaR_99', predicted_col='predicted_log_returns')

(0.061988267990688906, 3.4833730032317476)

In [25]:
diagnostics.compute_hit_rate(predicted=snp_garch_fbm_var['predicted_log_returns'], actual=snp_garch_fbm_var['log_returns'])

Hit Rate: 51.00%

0.5099513489606369

In [26]:
plots.plot_var_violations(snp_garch_fbm_var, var_col='VaR_99', predicted_col='predicted_log_returns')

### VIX

In [27]:
VIX_processed = preprocess.preprocess_data(VIX_file, "vol", "log_vol_diff")
VIX_processed = utils.upscale_columns(
  VIX_processed, ['log_vol_diff'], SCALE
)
VIX_processed.head()

              vol  log_vol_diff
date
2015-01-05  19.92     11.308775
2015-01-06  21.12      5.849621
2015-01-07  19.31     -8.959736
2015-01-08  17.01    -12.682169
2015-01-09  17.55      3.125254

In [ ]:
vix_obj = utils.GarchFbmVolForecast(VIX_processed)
vix_garch_fbm = utils.apply_rolling_predictions_from_start(vix_obj, '2017-01-01', 250)

Day 252...
Day 253...
Day 254...
Day 255...
Day 256...
Day 257...
Day 258...
Day 259...
Day 260...
Day 261...
Day 262...
Day 263...
Day 264...
Day 265...
Day 266...
Day 267...
Day 268...
Day 269...
Day 270...
Day 271...
Day 272...
Day 273...
Day 274...
Day 275...
Day 276...
Day 277...
Day 278...
Day 279...
Day 280...
Day 281...
Day 282...
Day 283...
Day 284...
Day 285...
Day 286...
Day 287...
Day 288...
Day 289...
Day 290...
Day 291...
Day 292...
Day 293...
Day 294...
Day 295...
Day 296...
Day 297...
Day 298...
Day 299...
Day 300...
Day 301...
Day 302...
Day 303...
Day 304...
Day 305...
Day 306...
Day 307...
Day 308...
Day 309...
Day 310...
Day 311...
Day 312...
Day 313...
Day 314...
Day 315...
Day 316...
Day 317...
Day 318...
Day 319...
Day 320...
Day 321...
Day 322...
Day 323...
Day 324...
Day 325...
Day 326...
Day 327...
Day 328...
Day 329...
Day 330...
Day 331...
Day 332...
Day 333...
Day 334...
Day 335...
Day 336...
Day 337...
Day 338...
Day 339...
Day 340...
Day 341...
Day 342...
Day 343...
Day 344...
Day 345...
Day 346...
Day 347...
Day 348...
Day 349...
Day 350...
Day 351...
Day 352...
Day 353...
Day 354...
Day 355...
Day 356...
Day 357...
Day 358...
Day 359...
Day 360...
Day 361...
Day 362...
Day 363...
Day 364...
Day 365...
Day 366...
Day 367...
Day 368...
Day 369...
Day 370...
Day 371...
Day 372...
Day 373...
Day 374...
Day 375...
Day 376...
Day 377...
Day 378...
Day 379...
Day 380...
Day 381...
Day 382...
Day 383...
Day 384...
Day 385...
Day 386...
Day 387...
Day 388...
Day 389...
Day 390...
Day 391...
Day 392...
Day 393...
Day 394...
Day 395...
Day 396...
Day 397...
Day 398...
Day 399...
Day 400...
Day 401...
Day 402...
Day 403...
Day 404...
Day 405...
Day 406...
Day 407...
Day 408...
Day 409...
Day 410...
Day 411...
Day 412...
Day 413...
Day 414...
Day 415...
Day 416...
Day 417...
Day 418...
Day 419...
Day 420...
Day 421...
Day 422...
Day 423...
Day 424...
Day 425...
Day 426...
Day 427...
Day 428...
Day 429...
Day 430...
Day 431...
Day 432...
Day 433...
Day 434...
Day 435...
Day 436...
Day 437...
Day 438...
Day 439...
Day 440...
Day 441...
Day 442...
Day 443...
Day 444...
Day 445...
Day 446...
Day 447...
Day 448...
Day 449...
Day 450...
Day 451...
Day 452...
Day 453...
Day 454...
Day 455...
Day 456...
Day 457...
Day 458...
Day 459...
Day 460...
Day 461...
Day 462...
Day 463...
Day 464...
Day 465...
Day 466...
Day 467...
Day 468...
Day 469...
Day 470...
Day 471...
Day 472...
Day 473...
Day 474...
Day 475...
Day 476...
Day 477...
Day 478...
Day 479...
Day 480...
Day 481...
Day 482...
Day 483...
Day 484...
Day 485...
Day 486...
Day 487...
Day 488...
Day 489...
Day 490...
Day 491...
Day 492...
Day 493...
Day 494...
Day 495...
Day 496...
Day 497...
Day 498...
Day 499...
Day 500...
Day 501...
Day 502...
Day 503...
Day 504...
Day 505...
Day 506...
Day 507...
Day 508...
Day 509...
Day 510...
Day 511...
Day 512...
Day 513...
Day 514...
Day 515...
Day 516...
Day 517...
Day 518...
Day 519...
Day 520...
Day 521...
Day 522...
Day 523...
Day 524...
Day 525...
Day 526...
Day 527...
Day 528...
Day 529...
Day 530...
Day 531...
Day 532...
Day 533...
Day 534...
Day 535...
Day 536...
Day 537...
Day 538...
Day 539...
Day 540...
Day 541...
Day 542...
Day 543...
Day 544...
Day 545...
Day 546...
Day 547...
Day 548...
Day 549...
Day 550...
Day 551...
Day 552...
Day 553...
Day 554...
Day 555...
Day 556...
Day 557...
Day 558...
Day 559...
Day 560...
Day 561...
Day 562...
Day 563...
Day 564...
Day 565...
Day 566...
Day 567...
Day 568...
Day 569...
Day 570...
Day 571...
Day 572...
Day 573...
Day 574...
Day 575...
Day 576...
Day 577...
Day 578...
Day 579...
Day 580...
Day 581...
Day 582...
Day 583...
Day 584...
Day 585...
Day 586...
Day 587...
Day 588...
Day 589...
Day 590...
Day 591...
Day 592...
Day 593...
Day 594...
Day 595...
Day 596...
Day 597...
Day 598...
Day 599...
Day 600...
Day 601...
Day 602...
Day 603...
Day 604...
Day 605...
Day 606...
Day 607...
Day 608...
Day 609...
Day 610...
Day 611...
Day 612...
Day 613...
Day 614...
Day 615...
Day 616...
Day 617...
Day 618...
Day 619...
Day 620...
Day 621...
Day 622...
Day 623...
Day 624...
Day 625...
Day 626...
Day 627...
Day 628...
Day 629...
Day 630...
Day 631...
Day 632...
Day 633...
Day 634...
Day 635...
Day 636...
Day 637...
Day 638...
Day 639...
Day 640...
Day 641...
Day 642...
Day 643...
Day 644...
Day 645...
Day 646...
Day 647...
Day 648...
Day 649...
Day 650...
Day 651...
Day 652...
Day 653...
Day 654...
Day 655...
Day 656...
Day 657...
Day 658...
Day 659...
Day 660...
Day 661...
Day 662...
Day 663...
Day 664...
Day 665...
Day 666...
Day 667...
Day 668...
Day 669...
Day 670...
Day 671...
Day 672...
Day 673...
Day 674...
Day 675...
Day 676...
Day 677...
Day 678...
Day 679...
Day 680...
Day 681...
Day 682...
Day 683...
Day 684...
Day 685...
Day 686...
Day 687...
Day 688...
Day 689...
Day 690...
Day 691...
Day 692...
Day 693...
Day 694...
Day 695...
Day 696...
Day 697...
Day 698...
Day 699...
Day 700...
Day 701...
Day 702...
Day 703...
Day 704...
Day 705...
Day 706...
Day 707...
Day 708...
Day 709...
Day 710...
Day 711...
Day 712...
Day 713...
Day 714...
Day 715...
Day 716...
Day 717...
Day 718...
Day 719...
Day 720...
Day 721...
Day 722...
Day 723...
Day 724...
Day 725...
Day 726...
Day 727...
Day 728...
Day 729...
Day 730...
Day 731...
Day 732...
Day 733...
Day 734...
Day 735...
Day 736...
Day 737...
Day 738...
Day 739...
Day 740...
Day 741...
Day 742...
Day 743...
Day 744...
Day 745...
Day 746...
Day 747...
Day 748...
Day 749...
Day 750...
Day 751...
Day 752...
Day 753...
Day 754...
Day 755...
Day 756...
Day 757...
Day 758...
Day 759...
Day 760...
Day 761...
Day 762...
Day 763...
Day 764...
Day 765...
Day 766...
Day 767...
Day 768...
Day 769...
Day 770...
Day 771...
Day 772...
Day 773...
Day 774...
Day 775...
Day 776...
Day 777...
Day 778...
Day 779...
Day 780...
Day 781...
Day 782...
Day 783...
Day 784...
Day 785...
Day 786...
Day 787...
Day 788...
Day 789...
Day 790...
Day 791...
Day 792...
Day 793...
Day 794...
Day 795...
Day 796...
Day 797...
Day 798...
Day 799...
Day 800...
Day 801...
Day 802...
Day 803...
Day 804...
Day 805...
Day 806...
Day 807...
Day 808...
Day 809...
Day 810...
Day 811...
Day 812...
Day 813...
Day 814...
Day 815...
Day 816...
Day 817...
Day 818...
Day 819...
Day 820...
Day 821...
Day 822...
Day 823...
Day 824...
Day 825...
Day 826...
Day 827...
Day 828...
Day 829...
Day 830...
Day 831...
Day 832...
Day 833...
Day 834...
Day 835...
Day 836...
Day 837...
Day 838...
Day 839...
Day 840...
Day 841...
Day 842...
Day 843...
Day 844...
Day 845...
Day 846...
Day 847...
Day 848...
Day 849...
Day 850...
Day 851...
Day 852...
Day 853...
Day 854...
Day 855...
Day 856...
Day 857...
Day 858...
Day 859...
Day 860...
Day 861...
Day 862...
Day 863...
Day 864...
Day 865...
Day 866...
Day 867...
Day 868...
Day 869...
Day 870...
Day 871...
Day 872...
Day 873...
Day 874...
Day 875...
Day 876...
Day 877...
Day 878...
Day 879...
Day 880...
Day 881...
Day 882...
Day 883...
Day 884...
Day 885...
Day 886...
Day 887...
Day 888...
Day 889...
Day 890...
Day 891...
Day 892...
Day 893...
Day 894...
Day 895...
Day 896...
Day 897...
Day 898...
Day 899...
Day 900...
Day 901...
Day 902...
Day 903...
Day 904...
Day 905...
Day 906...
Day 907...
Day 908...
Day 909...
Day 910...
Day 911...
Day 912...
Day 913...
Day 914...
Day 915...
Day 916...
Day 917...
Day 918...
Day 919...
Day 920...
Day 921...
Day 922...
Day 923...
Day 924...
Day 925...
Day 926...
Day 927...
Day 928...
Day 929...
Day 930...
Day 931...
Day 932...
Day 933...
Day 934...
Day 935...
Day 936...
Day 937...
Day 938...
Day 939...
Day 940...
Day 941...
Day 942...
Day 943...
Day 944...
Day 945...
Day 946...
Day 947...
Day 948...
Day 949...
Day 950...
Day 951...
Day 952...
Day 953...
Day 954...
Day 955...
Day 956...
Day 957...
Day 958...
Day 959...
Day 960...
Day 961...
Day 962...
Day 963...
Day 964...
Day 965...
Day 966...
Day 967...
Day 968...
Day 969...
Day 970...
Day 971...
Day 972...
Day 973...
Day 974...
Day 975...
Day 976...
Day 977...
Day 978...
Day 979...
Day 980...
Day 981...
Day 982...
Day 983...
Day 984...
Day 985...
Day 986...
Day 987...
Day 988...
Day 989...
Day 990...
Day 991...
Day 992...
Day 993...
Day 994...
Day 995...
Day 996...
Day 997...
Day 998...
Day 999...
Day 1000...
Day 1001...
Day 1002...
Day 1003...
Day 1004...
Day 1005...
Day 1006...
Day 1007...
Day 1008...
Day 1009...
Day 1010...
Day 1011...
Day 1012...
Day 1013...
Day 1014...
Day 1015...
Day 1016...
Day 1017...
Day 1018...
Day 1019...
Day 1020...
Day 1021...
Day 1022...
Day 1023...
Day 1024...
Day 1025...
Day 1026...
Day 1027...
Day 1028...
Day 1029...
Day 1030...
Day 1031...
Day 1032...
Day 1033...
Day 1034...
Day 1035...
Day 1036...
Day 1037...
Day 1038...
Day 1039...
Day 1040...
Day 1041...
Day 1042...
Day 1043...
Day 1044...
Day 1045...
Day 1046...
Day 1047...
Day 1048...
Day 1049...
Day 1050...
Day 1051...
Day 1052...
Day 1053...
Day 1054...
Day 1055...
Day 1056...
Day 1057...
Day 1058...
Day 1059...
Day 1060...
Day 1061...
Day 1062...
Day 1063...
Day 1064...
Day 1065...
Day 1066...
Day 1067...
Day 1068...
Day 1069...
Day 1070...
Day 1071...
Day 1072...
Day 1073...
Day 1074...
Day 1075...
Day 1076...
Day 1077...
Day 1078...
Day 1079...
Day 1080...
Day 1081...
Day 1082...
Day 1083...
Day 1084...
Day 1085...
Day 1086...
Day 1087...
Day 1088...
Day 1089...
Day 1090...
Day 1091...
Day 1092...
Day 1093...
Day 1094...
Day 1095...
Day 1096...
Day 1097...
Day 1098...
Day 1099...
Day 1100...
Day 1101...
Day 1102...
Day 1103...
Day 1104...
Day 1105...
Day 1106...
Day 1107...
Day 1108...

In [ ]:
vix_garch_fbm= utils.compute_log_returns(
  vix_garch_fbm,
  VIX_processed,
  "predicted",
  "predicted_log_vol_diff"
)
vix_garch_fbm.head()

In [ ]:
# Rescale back conditional volatility
vix_garch_fbm_rescaled = utils.rescale_columns(
  vix_garch_fbm,
  ['log_vol_diff'],
  SCALE
)

vix_garch_fbm_with_predictions = vix_garch_fbm_rescaled.dropna()
vix_garch_fbm_rescaled = vix_garch_fbm_with_predictions.copy()
diagnostics.in_sample_diagnostics(vix_garch_fbm_rescaled['predicted_log_vol_diff'], vix_garch_fbm_rescaled['log_vol_diff'], vix_garch_fbm_rescaled['conditional_vol'])

In [ ]:
vix_garch_fbm_var = vix_garch_fbm_rescaled
vix_garch_fbm_var['VaR_99'] = vix_garch_fbm_var['predicted_log_vol_diff'].rolling(250).quantile(0.01)  # 1st percentile
diagnostics.compute_var_violations(vix_garch_fbm_var, 'VaR_99', 'predicted_log_vol_diff')

In [ ]:
utils.compute_rmse(vix_garch_fbm_rescaled, 'log_vol_diff', 'predicted_log_vol_diff')

In [ ]:
diagnostics.bernoulli_coverage_test(vix_garch_fbm_var, var_col='VaR_99', predicted_col='predicted_log_vol_diff')

In [ ]:
diagnostics.compute_hit_rate(predicted=vix_garch_fbm_var['predicted_log_vol_diff'], actual=vix_garch_fbm_var['log_vol'])

In [ ]:
plots.plot_var_violations(vix_garch_fbm_var, var_col='VaR_99', predicted_col='predicted_log_vol_diff')