In [1]:
import plotly.graph_objects as go
import diagnostics
import os
import preprocess
import plots
import utils
import numpy as np
import pandas as pd

c:\Users\joshu\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
c:\Users\joshu\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.4' currently installed).
  from pandas.core import (

### Setup

In [ ]:
SNP_file = './data/S&P 500 Index.csv'
VIX_file = './data/S&P 500 VIX.csv'

In [3]:
# Scale is applied to log returns in order to improve numerical stability of models
SCALE = 100

### S&P500

In [4]:
SNP_processed = preprocess.preprocess_data(SNP_file, 'price', 'log_returns')
SNP_processed = utils.upscale_columns(
  SNP_processed, ['log_returns'], SCALE
)
SNP_processed.head()

              price  log_returns
date
2015-01-05  2020.58    -1.844722
2015-01-06  2002.61    -0.893327
2015-01-07  2025.90     1.156272
2015-01-08  2062.14     1.773023
2015-01-09  2044.81    -0.843940

In [5]:
snp_obj = utils.GarchFbmReturnForecast(SNP_processed)
snp_obj.df.head()

              price  log_returns
date
2015-01-05  2020.58    -1.844722
2015-01-06  2002.61    -0.893327
2015-01-07  2025.90     1.156272
2015-01-08  2062.14     1.773023
2015-01-09  2044.81    -0.843940

In [ ]:
snp_garch_fbm = utils.apply_rolling_predictions_from_start(snp_obj, '2017-01-01', 250)
snp_garch_fbm.head()

In [7]:
snp_garch_fbm= utils.compute_log_returns(
  snp_garch_fbm,
  SNP_processed,
  "predicted",
  "predicted_log_returns"
)
snp_garch_fbm.head()

,predicted,conditional_vol,predicted_log_returns,price,log_returns
2016-01-06,2016.873961,0.010580,0.001736,1990.26,-1.320219
2016-01-07,1990.540944,0.009492,-0.013142,1943.09,-2.398579
2016-01-08,1944.089305,0.010463,-0.023613,1922.03,-1.089757
2016-01-11,1920.153003,0.013987,-0.012389,1923.67,0.085290
2016-01-12,1923.652506,0.012946,0.001821,1938.68,0.777251

In [8]:
# Rescale back scaled columns
snp_garch_fbm = utils.downscale_columns(
  snp_garch_fbm, ['log_returns'], SCALE
)
diagnostics.in_sample_diagnostics(snp_garch_fbm['predicted_log_returns'], snp_garch_fbm['log_returns'], snp_garch_fbm['conditional_vol'])

Jarque-Bera test p-value: 0.00000
Ljung-Box (residuals) p-value, 0.00000
Ljung-Box (residuals^2) p-value, 0.00000

In [9]:
snp_garch_fbm.head()

,predicted,conditional_vol,predicted_log_returns,price,log_returns
2016-01-06,2016.873961,0.010580,0.001736,1990.26,-0.013202
2016-01-07,1990.540944,0.009492,-0.013142,1943.09,-0.023986
2016-01-08,1944.089305,0.010463,-0.023613,1922.03,-0.010898
2016-01-11,1920.153003,0.013987,-0.012389,1923.67,0.000853
2016-01-12,1923.652506,0.012946,0.001821,1938.68,0.007773

In [10]:
snp_garch_fbm_var = snp_garch_fbm
snp_garch_fbm_var['VaR_99'] = snp_garch_fbm_var['predicted_log_returns'].rolling(250).quantile(0.01)
diagnostics.compute_var_violations(snp_garch_fbm_var, 'VaR_99', 'predicted_log_returns')

{'actual_exceedances': 32,
 'expected_exceedances': 20.12000000000002,
 'violation_ratio': 1.5904572564612312}

In [11]:
diagnostics.compute_rmse(snp_garch_fbm_var, 'log_returns', 'predicted_log_returns')

0.017291704611987098

In [12]:
diagnostics.bernoulli_coverage_test(snp_garch_fbm_var, var_col='VaR_99', predicted_col='predicted_log_returns')

(0.01423812692607851, 6.00837584127612)

In [13]:
diagnostics.compute_hit_rate(predicted=snp_garch_fbm_var['predicted_log_returns'], actual=snp_garch_fbm_var['log_returns'])

Hit Rate: 48.52%

0.4851835471030517

In [14]:
plots.plot_var_violations(snp_garch_fbm_var, var_col='VaR_99', predicted_col='predicted_log_returns')

In [15]:
plots.actual_vs_predicted_time_series_plot(
  snp_garch_fbm_var,
  'log_returns',
  'predicted_log_returns',
  'Log Returns'
)

### VIX

In [16]:
VIX_processed = preprocess.preprocess_data(VIX_file, "vol", "log_vol_diff")
VIX_processed = utils.upscale_columns(
  VIX_processed, ['log_vol_diff'], SCALE
)
VIX_processed.head()

              vol  log_vol_diff
date
2015-01-05  19.92     11.308775
2015-01-06  21.12      5.849621
2015-01-07  19.31     -8.959736
2015-01-08  17.01    -12.682169
2015-01-09  17.55      3.125254

In [ ]:
vix_obj = utils.GarchFbmVolForecast(VIX_processed)
vix_garch_fbm = utils.apply_rolling_predictions_from_start(vix_obj, '2017-01-01', 250)

In [18]:
vix_garch_fbm= utils.compute_log_returns(
  vix_garch_fbm,
  VIX_processed,
  "predicted",
  "predicted_log_vol_diff"
)
vix_garch_fbm.head()

,predicted,conditional_vol,predicted_log_vol_diff,vol,log_vol_diff
2016-01-06,19.524493,0.090864,-0.061627,20.59,6.263003
2016-01-07,20.675450,0.085081,0.057277,24.99,19.367022
2016-01-08,25.077619,0.082464,0.193029,27.01,7.773142
2016-01-11,27.394529,0.115035,0.088368,24.30,-10.573082
2016-01-12,24.559223,0.103393,-0.109256,22.47,-7.829526

In [19]:
vix_garch_fbm_rescaled = utils.downscale_columns(
  vix_garch_fbm,
  ['log_vol_diff'],
  SCALE
)

vix_garch_fbm_with_predictions = vix_garch_fbm_rescaled.dropna()
vix_garch_fbm_rescaled = vix_garch_fbm_with_predictions.copy()
diagnostics.in_sample_diagnostics(vix_garch_fbm_rescaled['predicted_log_vol_diff'], vix_garch_fbm_rescaled['log_vol_diff'], vix_garch_fbm_rescaled['conditional_vol'])

Jarque-Bera test p-value: 0.00000
Ljung-Box (residuals) p-value, 0.00000
Ljung-Box (residuals^2) p-value, 0.00000

In [20]:
vix_garch_fbm_var = vix_garch_fbm_rescaled
vix_garch_fbm_var['VaR_99'] = vix_garch_fbm_var['predicted_log_vol_diff'].rolling(250).quantile(0.01)  # 1st percentile
diagnostics.compute_var_violations(vix_garch_fbm_var, 'VaR_99', 'predicted_log_vol_diff')

{'actual_exceedances': 27,
 'expected_exceedances': 20.33000000000002,
 'violation_ratio': 1.3280865715691084}

In [21]:
diagnostics.compute_rmse(vix_garch_fbm_rescaled, 'log_vol_diff', 'predicted_log_vol_diff')

0.11622724873832929

In [22]:
diagnostics.bernoulli_coverage_test(vix_garch_fbm_var, var_col='VaR_99', predicted_col='predicted_log_vol_diff')

(0.15687978116304335, 2.004047748766993)

In [23]:
diagnostics.compute_hit_rate(predicted=vix_garch_fbm_var['predicted_log_vol_diff'], actual=vix_garch_fbm_var['log_vol_diff'])

Hit Rate: 49.08%

0.49079754601226994

In [24]:
plots.plot_var_violations(vix_garch_fbm_var, var_col='VaR_99', predicted_col='predicted_log_vol_diff')

In [25]:
plots.actual_vs_predicted_time_series_plot(
  vix_garch_fbm_var,
  'log_vol_diff',
  'predicted_log_vol_diff',
  'Log Returns on Volatility'
)